import { useEffect, useRef } from "react";
import { MapPin, Video, BarChart3, Network, Star } from "lucide-react";
import GlowingCard from "@/components/GlowingCard";

export default function Impact() {
  const sectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const section = sectionRef.current;
    if (!section) return;

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("visible");
          }
        });
      },
      { threshold: 0.1, rootMargin: "0px 0px -50px 0px" }
    );

    section.querySelectorAll(".fade-in").forEach((el) => observer.observe(el));

    return () => observer.disconnect();
  }, []);

  const stats = [
    { number: "150+", label: "Women Trained", subtitle: "Across 12 villages", glow: "purple" },
    { number: "85%", label: "Employment Rate", subtitle: "Within 6 months", glow: "blue" },
    { number: "$50K+", label: "Total Earnings", subtitle: "Generated by graduates", glow: "purple" }
  ];

  const testimonials = [
    {
      name: "Fatima Khan",
      role: "Web Developer • Lahore",
      image: "https://images.unsplash.com/photo-1494790108755-2616b612b47c?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150",
      testimonial: "ReCode didn't just teach me to code – it gave me a new identity. From a flood victim to a freelance web developer earning enough to support my family. The journey seemed impossible, but their support made it real.",
      glow: "purple"
    },
    {
      name: "Aisha Malik", 
      role: "Digital Marketer • Remote",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150",
      testimonial: "The digital marketing course opened doors I never knew existed. Now I manage social media for three international clients from my home in a small village. Technology has truly broken geographical barriers.",
      glow: "blue"
    }
  ];

  const comingSoonItems = [
    { icon: Video, title: "Video Stories", description: "Documentary series featuring graduate journeys", glow: "purple" },
    { icon: BarChart3, title: "Impact Dashboard", description: "Real-time tracking of program outcomes", glow: "blue" },
    { icon: Network, title: "Alumni Network", description: "Connect graduates for mentorship and collaboration", glow: "purple" }
  ];

  return (
    <div ref={sectionRef} className="py-20 px-4 sm:px-6 lg:px-8 bg-muted/20">
      <div className="max-w-6xl mx-auto">
        <div className="text-center mb-16 fade-in">
          <h2 className="text-4xl sm:text-5xl font-orbitron font-bold mb-6 text-neon">
            Our Impact
          </h2>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
            Real stories from real women whose lives have been transformed through technology education.
          </p>
        </div>

        {/* Stats */}
        <div className="grid md:grid-cols-3 gap-8 mb-16">
          {stats.map((stat, index) => (
            <div key={index} className="fade-in">
              <GlowingCard 
                glowColor={stat.glow as "purple" | "blue"} 
                className="text-center p-8"
                testId={`stat-${stat.label.toLowerCase().replace(/\s+/g, '-')}`}
              >
                <div className={`text-4xl font-orbitron font-bold mb-2 ${
                  stat.glow === "purple" ? "text-neon" : "text-neon-blue"
                }`}>
                  {stat.number}
                </div>
                <div className="text-lg text-foreground font-semibold mb-2">
                  {stat.label}
                </div>
                <div className="text-sm text-muted-foreground">
                  {stat.subtitle}
                </div>
              </GlowingCard>
            </div>
          ))}
        </div>

        {/* Testimonials */}
        <div className="grid md:grid-cols-2 gap-8 mb-16">
          {testimonials.map((testimonial, index) => (
            <div key={index} className="fade-in">
              <GlowingCard 
                glowColor={testimonial.glow as "purple" | "blue"}
                testId={`testimonial-${testimonial.name.toLowerCase().replace(/\s+/g, '-')}`}
              >
                <div className="flex items-center mb-6">
                  <img 
                    src={testimonial.image} 
                    alt={`${testimonial.name} - Program Graduate`}
                    className={`w-16 h-16 rounded-full mr-4 ${
                      testimonial.glow === "purple" ? "neon-glow" : "neon-glow-blue"
                    }`}
                  />
                  <div>
                    <h4 className="text-lg font-semibold text-foreground">
                      {testimonial.name}
                    </h4>
                    <p className={`text-sm ${
                      testimonial.glow === "purple" ? "text-neon" : "text-neon-blue"
                    }`}>
                      {testimonial.role}
                    </p>
                  </div>
                </div>
                <p className="text-foreground leading-relaxed mb-4">
                  "{testimonial.testimonial}"
                </p>
                <div className="flex text-secondary">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-4 h-4 fill-current" />
                  ))}
                </div>
              </GlowingCard>
            </div>
          ))}
        </div>

        {/* Map Visualization */}
        <div className="mb-16 fade-in">
          <GlowingCard testId="map-visualization">
            <h3 className="text-2xl font-orbitron font-bold text-center text-neon mb-8">
              Our Reach
            </h3>
            <div className="relative h-64 bg-gradient-to-br from-primary/20 to-secondary/20 rounded-xl overflow-hidden">
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="text-center">
                  <MapPin className="w-16 h-16 text-neon mb-4 mx-auto" />
                  <p className="text-xl font-semibold text-foreground">
                    Interactive Impact Map
                  </p>
                  <p className="text-sm text-muted-foreground">
                    Coming Soon - Visualizing our growing network across Pakistan
                  </p>
                </div>
              </div>
              {/* Decorative elements */}
              <div className="absolute top-4 left-4 w-3 h-3 bg-primary rounded-full neon-glow animate-pulse" />
              <div className="absolute top-12 right-8 w-2 h-2 bg-secondary rounded-full neon-glow-blue animate-pulse" />
              <div className="absolute bottom-8 left-12 w-4 h-4 bg-primary rounded-full neon-glow animate-pulse" />
              <div className="absolute bottom-4 right-4 w-2 h-2 bg-secondary rounded-full neon-glow-blue animate-pulse" />
            </div>
          </GlowingCard>
        </div>

        {/* Coming Soon Cards */}
        <div className="grid md:grid-cols-3 gap-6">
          {comingSoonItems.map((item, index) => {
            const IconComponent = item.icon;
            return (
              <div key={index} className="fade-in">
                <GlowingCard 
                  glowColor={item.glow as "purple" | "blue"}
                  className="text-center"
                  testId={`coming-soon-${item.title.toLowerCase().replace(/\s+/g, '-')}`}
                >
                  <IconComponent className={`w-12 h-12 mx-auto mb-4 ${
                    item.glow === "purple" ? "text-neon" : "text-neon-blue"
                  }`} />
                  <h4 className="text-lg font-orbitron font-bold text-foreground mb-2">
                    {item.title}
                  </h4>
                  <p className="text-sm text-muted-foreground mb-4">
                    {item.description}
                  </p>
                  <span className={`inline-block px-3 py-1 text-xs rounded-full font-semibold ${
                    item.glow === "purple" 
                      ? "bg-primary/20 text-primary" 
                      : "bg-secondary/20 text-secondary"
                  }`}>
                    Coming Soon
                  </span>
                </GlowingCard>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
